bitpay:
  requestURL: "https://bitpay.ir/payment/gateway-send"
  verifyURL: "https://bitpay.ir/payment/gateway-result-second"
  payURL: "https://bitpay.ir/payment/"

mellat:
  url: "https://bpm.shaparak.ir/pgwchannel/services/pgw?wsdl"
  gatewayURL: "https://bpm.shaparak.ir/pgwchannel/startpay.mellat"

saman:
  requestURL: "https://sep.shaparak.ir/OnlinePG/OnlinePG"
  payURL: "https://sep.shaparak.ir/OnlinePG/SendToken"
  verifyURL: "https://sep.shaparak.ir/verifyTxnRandomSessionkey/ipg/VerifyTransaction"
  reverseURL: "https://sep.shaparak.ir/verifyTxnRandomSessionkey/ipg/ReverseTransaction"

zarinpal:
  requestURL: "https://api.zarinpal.com/pg/v4/payment/request.json"
  payURL: "https://www.zarinpal.com/pg/StartPay/"
  verifyURL: "https://api.zarinpal.com/pg/v4/payment/verify.json"
  inquiryURL: "https://api.zarinpal.com/pg/v4/payment/inquiry.json"
  unverifiedURL: "https://api.zarinpal.com/pg/v4/payment/unVerified.json"

saderat:
  TokenURL: "https://sepehr.shaparak.ir:8081/V1/PeymentApi/GetToken"
  PaymentURL: "https://mabna.shaparak.ir:8080/Pay"
  AdviceURL: "https://mabna.shaparak.ir:8082/ipg.svc?wsdl"
  RollbackURL: "https://mabna.shaparak.ir:8082/ipg.svc?wsdl"
